// src/locales/en.ts

export const en = {
  // Header / Navigation
  nav: {
    voucher: "Voucher",
    contact: "Contact Us",
    emergency: "Emergency",
    quote: "Get Quote",
    agentAccess: "Agent Access",
  },
  
  // Footer
  footer: {
    aboutUs: "About Us",
    termsAndConditions: "Terms and Conditions",
    privacyPolicy: "Privacy Policy",
    followUs: "Follow Us",
    quickLinks: "Quick Links",
    whoWeAre: "Who We Are",
    products: "Products",
    faq: "FAQ",
    contact: "Contact Us",
    travelTips: "Travel Tips",
    support: "Support",
    generalConditions: "General Conditions",
    webUsageConditions: "Web Usage Conditions",
    contactInfo: "Contact Information",
    address: "2050 W 84th St, Hialeah, FL 33014, USA",
    allRightsReserved: "All rights reserved",
  },
  
  // Contact page
  contact: {
    title: "Contact Us",
    formTitle: "Contact Form",
    personalData: "Personal Information",
    name: "First Name",
    lastname: "Last Name",
    email: "Email",
    phone: "Phone",
    message: "Message",
    comments: "Comments",
    send: "Send",
    sending: "Sending...",
    successMessage: "Message sent successfully",
    errorMessage: "Error sending message",
    required: "This field is required",
    invalidEmail: "Invalid email",
    check1: "I accept the terms and conditions",
    check2: "I accept the privacy policy",
    mustAcceptTerms: "You must accept the terms and conditions",
  },
  
  // Emergency page
  emergency: {
    title: "Emergency",
    callUs: "Call Us",
    available24h: "Available 24/7",
    emergencyNumber: "Emergency Number",
    whatToDo: "What to do in an emergency?",
  },
  
  // Plans page
  plans: {
    title: "Our Plans",
    selectPlan: "Select Plan",
    compare: "Compare",
    viewDetails: "View Details",
    from: "From",
    perPerson: "Per Person",
    coverage: "Coverage",
    benefits: "Benefits",
  },
  
  // FAQ page
  faq: {
    title: "Frequently Asked Questions",
    question: "Question",
    answer: "Answer",
    searchPlaceholder: "Search question...",
    noResults: "No results found",
  },
  
  // Join Sales Team
  joinSales: {
    title: "Join Our Sales Team",
    apply: "Apply",
    firstName: "First Name",
    lastName: "Last Name",
    position: "Position",
    experience: "Experience",
    resume: "Resume",
    uploadResume: "Upload Resume",
  },
  
  // Login
  login: {
    title: "Login",
    email: "Email",
    password: "Password",
    submit: "Sign In",
    forgotPassword: "Forgot your password?",
    noAccount: "Don't have an account?",
    register: "Sign Up",
    rememberMe: "Remember me",
  },
  
  // Voucher
  voucher: {
    title: 'Your Plan',
    formTitle: 'Consult Voucher',
    userInfo: 'User Information',
    name: 'Name',
    lastname: 'Last Name',
    birthdate: 'Birth Date',
    voucherNumber: 'Voucher Number',
    voucherCode: 'Voucher Code',
    search: 'Search',
    download: 'Download',
    downloadPDF: 'Download PDF',
    back: 'Back',
    notFound: 'Voucher not found',
    details: 'Voucher Details',
    statusLabel: 'Status',
    passenger: 'Passenger',
    validFrom: 'Valid from',
    validUntil: 'Valid until',
    
    // Modal info
    infoAboutVoucher: 'Voucher Information',
    voucherDetails: 'Voucher Details',
    
    // Tabs
    tabVoucher: 'Voucher',
    tabPassengers: 'Passengers',
    tabAdditional: 'Additional',
    tabDisabled: 'No Data',
    
    // Passengers
    passengers: 'Passengers',
    passengerLabel: 'Passenger',
    noPassengers: 'No passenger information available',
    document: 'Document',
    email: 'Email',
    phone: 'Phone',
    gender: 'Gender',
    country: 'Country',
    
    // Raiders/Additional
    raiders: 'Special Services',
    additionalServices: 'Additional Services',
    noRaiders: 'No additional benefits',
    raiderTitle: 'Special Service',
    raiderId: 'Raider ID',
    raiderName: 'Service Name',
    raiderValue: 'Value',
    raiderCost: 'Cost',
    raiderDescription: 'Description',
    
    // States
    loading: 'Searching voucher...',
    loadingMessage: 'Please wait...',
    
    // Error messages
    notFoundTitle: 'Voucher not found',
    notFoundMessage: 'No voucher was found with the provided information.',
    error403Title: 'Access Error',
    error403Message: 'The provided information is incorrect or access was denied.',
    incompleteTitle: 'Incomplete Data',
    incompleteMessage: 'Please complete all required fields to search for the voucher.',
    noDataPdf: 'No data to generate PDF',
    generatedBy: 'Generated by Voyager Travel Assist - ',
    
    // Voucher fields
    voucherKeys: {
      codigo: 'Code',
      salida: 'Departure Date',
      retorno: 'Return Date',
      programaplan: 'Plan Program',
      nombre_contacto: 'Contact Name',
      email_contacto: 'Contact Email',
      telefono_contacto: 'Contact Phone',
      comentarios: 'Comments',
      nombre_agencia: 'Agency Name',
      total: 'Total',
      fecha: 'Purchase Date',
      statusKey: 'Status',
      origin: 'Origin',
      dest: 'Destination',
    },
    
    // Voucher statuses
    status: {
      '1': 'Active',
      '2': 'To activate',
      '4': 'Invalid',
      '5': 'Annulled',
    },
  },
  
  // Common
  common: {
    loading: 'Loading...',
    error: 'Error',
    success: 'Success',
    cancel: 'Cancel',
    confirm: 'Confirm',
    close: 'Close',
    save: 'Save',
    edit: 'Edit',
    delete: 'Delete',
    search: 'Search',
    back: 'Back',
    next: 'Next',
    previous: 'Previous',
    viewMore: 'View more',
    viewLess: 'View less',
  },
};
